[gin]
mode="debug"
addr="192.168.1.4:8080"

[mysql]
addr="127.0.0.1"
port="3306"
config="charset=utf8mb4&parseTime=True&loc=Local"
db="douyin1"
username="root"
password="Hacker.123"

[redis]
addr="127.0.0.1:6379"
password=""
db=6
